#!/bin/bash

# Go to the parent directory of where this script is
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )/.." && pwd )"
cd $DIR

# Copy all the root terraform files into each tutorial
for d in */; do
  if [ "$d" != "scripts/" ] && [ "$d" != "ssh_keys/" ] && [ "$d" != "consul/" ]; then
    for f in *.tf; do
      echo "Copying $f into $d"
      cp "$f" "$d"
    done
  fi
done
